# Generated by Django 4.2.1 on 2023-08-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone_num', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'tbl_credentials',
            },
        ),
    ]
